"""RulesDocument_add_source_file_fields

Revision ID: 2396e7fd650f
Revises: b0df2e935acc
Create Date: 2026-03-30 19:12:49.152586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2396e7fd650f'
down_revision: Union[str, Sequence[str], None] = 'b0df2e935acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules_documents', sa.Column('source_storage_path', sa.String(length=1024), nullable=True))
    op.add_column('rules_documents', sa.Column('source_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules_documents', 'source_filename')
    op.drop_column('rules_documents', 'source_storage_path')
    # ### end Alembic commands ###
