"""Initial

Revision ID: b0df2e935acc
Revises: 
Create Date: 2026-03-22 14:35:53.416975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0df2e935acc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=False),
    sa.Column('task_name', sa.String(length=512), nullable=False),
    sa.Column('state', sa.Enum('STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='background_task_state'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('kwargs_snapshot', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index('ix_background_tasks_started_at', 'background_tasks', ['started_at'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('source_doc_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_title_lower', 'games', [sa.literal_column('lower(title)')], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rules_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'indexed', 'failed', name='rules_document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules_documents')
    op.drop_table('users')
    op.drop_index('ix_games_title_lower', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_background_tasks_started_at', table_name='background_tasks')
    op.drop_table('background_tasks')
    # ### end Alembic commands ###
