apiVersion: v1
kind: Secret
metadata:
  name: boardgame-secrets
  namespace: boardgame-prod
type: Opaque
stringData:
  POSTGRES_USER: "boardgame"
  POSTGRES_PASSWORD: "change_me"

  JWT_SECRET: "change_me"
  BOT_API_TOKEN: "change_me"
  BOT_TOKEN: "change_me"

  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "change_me"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "change_me"
